language: java
jdk:
  - openjdk8
cache:
  directories:
    - crayon-architect/cache
before_script: crayon-architect/clean.sh
script: crayon-architect/build.sh
deploy:
  skip_cleanup: true
  provider: script
  on:
    branch: master
  script: crayon-architect/deploy.sh

